import Head from "next/head";
import { Inter } from "next/font/google";
import TodoInput from "@/components/TodoInput";

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Todo App</h1>
        <TodoInput />
        <div>
          <ul>
            <li>task1</li>
            <li>task2</li>
          </ul>
        </div>
      </div>
    </>
  );
}
